include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_single_cascade_in_expression_statements: false
    sort_unnamed_constructors_first: false
    
analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
