include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    
analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
